# Company Holidays for Toyama Team - 2025
# Format: name: "Holiday Name", date: "YYYY-MM-DD", company_only: true/false

company_holidays:
  - name: "Makara Sankranthi"
    date: "2025-01-14"
    company_only: false
  - name: "Maha Shivarathri"
    date: "2025-02-26"
    company_only: false
  - name: "Ramzan"
    date: "2025-03-31"
    company_only: false
  - name: "May Day"
    date: "2025-05-01"
    company_only: false
  - name: "Bakrid"
    date: "2025-06-07"
    company_only: false
  - name: "Independence Day"
    date: "2025-08-15"
    company_only: false
  - name: "Ganesh Chaturthi"
    date: "2025-08-27"
    company_only: false
  - name: "Eid Milad"
    date: "2025-09-05"
    company_only: false
  - name: "Ayudha Pooja"
    date: "2025-10-01"
    company_only: false
  - name: "Gandhi Jayanthi"
    date: "2025-10-02"
    company_only: false
  - name: "Deepawali"
    date: "2025-10-21"
    company_only: false
  - name: "Kannada Rajyothsava"
    date: "2025-11-01"
    company_only: false